package com.decoutkhanqindev.dexreader.utils

fun String.toFullLanguageName(): String {
  val languageMap = mapOf(
    "en" to "English",
    "af" to "Afrikaans",
    "sq" to "Albanian",
    "ar" to "Arabic",
    "az" to "Azerbaijani",
    "eu" to "Basque",
    "be" to "Belarusian",
    "bn" to "Bengali",
    "bg" to "Bulgarian",
    "my" to "Burmese",
    "ca" to "Catalan",
    "zh" to "Chinese (Simplified)",
    "zh-hk" to "Chinese (Traditional)",
    "cv" to "Chuvash",
    "hr" to "Croatian",
    "cs" to "Czech",
    "da" to "Danish",
    "nl" to "Dutch",
    "eo" to "Esperanto",
    "et" to "Estonian",
    "fil" to "Filipino",
    "fi" to "Finnish",
    "fr" to "French",
    "ka" to "Georgian",
    "de" to "German",
    "el" to "Greek",
    "he" to "Hebrew",
    "hi" to "Hindi",
    "hu" to "Hungarian",
    "id" to "Indonesian",
    "ga" to "Irish",
    "it" to "Italian",
    "ja" to "Japanese",
    "jv" to "Javanese",
    "kk" to "Kazakh",
    "ko" to "Korean",
    "la" to "Latin",
    "lt" to "Lithuanian",
    "ms" to "Malay",
    "mn" to "Mongolian",
    "ne" to "Nepali",
    "no" to "Norwegian",
    "fa" to "Persian",
    "pl" to "Polish",
    "pt-br" to "Portuguese (BR)",
    "ro" to "Romanian",
    "ru" to "Russian",
    "sr" to "Serbian",
    "sk" to "Slovak",
    "sl" to "Slovenian",
    "es-la" to "Spanish (LATAM)",
    "sv" to "Swedish",
    "ta" to "Tamil",
    "te" to "Telugu",
    "th" to "Thai",
    "tr" to "Turkish",
    "uk" to "Ukrainian",
    "ur" to "Urdu",
    "uz" to "Uzbek",
    "vi" to "Vietnamese",
    "es" to "Spanish (LATAM)",
    "tl" to "Thailand"
  )
  return languageMap[this] ?: this
}

fun String.toLanguageCode(): String {
  val languageMap = mapOf(
    "English" to "en",
    "Afrikaans" to "af",
    "Albanian" to "sq",
    "Arabic" to "ar",
    "Azerbaijani" to "az",
    "Basque" to "eu",
    "Belarusian" to "be",
    "Bengali" to "bn",
    "Bulgarian" to "bg",
    "Burmese" to "my",
    "Catalan" to "ca",
    "Chinese (Simplified)" to "zh",
    "Chinese (Traditional)" to "zh-hk",
    "Chuvash" to "cv",
    "Croatian" to "hr",
    "Czech" to "cs",
    "Danish" to "da",
    "Dutch" to "nl",
    "Esperanto" to "eo",
    "Estonian" to "et",
    "Filipino" to "fil",
    "Finnish" to "fi",
    "French" to "fr",
    "Georgian" to "ka",
    "German" to "de",
    "Greek" to "el",
    "Hebrew" to "he",
    "Hindi" to "hi",
    "Hungarian" to "hu",
    "Indonesian" to "id",
    "Irish" to "ga",
    "Italian" to "it",
    "Japanese" to "ja",
    "Javanese" to "jv",
    "Kazakh" to "kk",
    "Korean" to "ko",
    "Latin" to "la",
    "Lithuanian" to "lt",
    "Malay" to "ms",
    "Mongolian" to "mn",
    "Nepali" to "ne",
    "Norwegian" to "no",
    "Persian" to "fa",
    "Polish" to "pl",
    "Portuguese (BR)" to "pt-br",
    "Romanian" to "ro",
    "Russian" to "ru",
    "Serbian" to "sr",
    "Slovak" to "sk",
    "Slovenian" to "sl",
    "Spanish (LATAM)" to "es-la",
    "Swedish" to "sv",
    "Tamil" to "ta",
    "Telugu" to "te",
    "Thai" to "th",
    "Turkish" to "tr",
    "Ukrainian" to "uk",
    "Urdu" to "ur",
    "Uzbek" to "uz",
    "Vietnamese" to "vi",
    "Spanish (LATAM)" to "es",
    "Thailand" to "tl"
  )
  return languageMap[this] ?: this
}